:: ==============================================================
:: File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
:: Version: 2014.2
:: Copyright (C) 2014 Xilinx Inc. All rights reserved.
:: 
:: ==============================================================


@echo off

C:/Xilinx/Vivado_HLS/2014.2/../../Vivado/2014.2/bin/vivado  -notrace -mode batch -source ipi_example.tcl -tclargs xc7z010clg400-1 ../xilinx_com_hls_mmult_accel_core_1_0.zip
