// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

#ifndef XMMULT_ACCEL_CORE_H
#define XMMULT_ACCEL_CORE_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmmult_accel_core_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_bus_BaseAddress;
} XMmult_accel_core_Config;
#endif

typedef struct {
    u32 Control_bus_BaseAddress;
    u32 IsReady;
} XMmult_accel_core;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMmult_accel_core_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMmult_accel_core_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMmult_accel_core_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMmult_accel_core_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMmult_accel_core_Initialize(XMmult_accel_core *InstancePtr, u16 DeviceId);
XMmult_accel_core_Config* XMmult_accel_core_LookupConfig(u16 DeviceId);
int XMmult_accel_core_CfgInitialize(XMmult_accel_core *InstancePtr, XMmult_accel_core_Config *ConfigPtr);
#else
int XMmult_accel_core_Initialize(XMmult_accel_core *InstancePtr, const char* InstanceName);
int XMmult_accel_core_Release(XMmult_accel_core *InstancePtr);
#endif

void XMmult_accel_core_Start(XMmult_accel_core *InstancePtr);
u32 XMmult_accel_core_IsDone(XMmult_accel_core *InstancePtr);
u32 XMmult_accel_core_IsIdle(XMmult_accel_core *InstancePtr);
u32 XMmult_accel_core_IsReady(XMmult_accel_core *InstancePtr);
void XMmult_accel_core_EnableAutoRestart(XMmult_accel_core *InstancePtr);
void XMmult_accel_core_DisableAutoRestart(XMmult_accel_core *InstancePtr);


void XMmult_accel_core_InterruptGlobalEnable(XMmult_accel_core *InstancePtr);
void XMmult_accel_core_InterruptGlobalDisable(XMmult_accel_core *InstancePtr);
void XMmult_accel_core_InterruptEnable(XMmult_accel_core *InstancePtr, u32 Mask);
void XMmult_accel_core_InterruptDisable(XMmult_accel_core *InstancePtr, u32 Mask);
void XMmult_accel_core_InterruptClear(XMmult_accel_core *InstancePtr, u32 Mask);
u32 XMmult_accel_core_InterruptGetEnabled(XMmult_accel_core *InstancePtr);
u32 XMmult_accel_core_InterruptGetStatus(XMmult_accel_core *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
