// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2014.2
// Copyright (C) 2014 Xilinx Inc. All rights reserved.
// 
// ==============================================================

/***************************** Include Files *********************************/
#include "xmmult_accel_core.h"

/************************** Function Implementation *************************/
#ifndef __linux__
int XMmult_accel_core_CfgInitialize(XMmult_accel_core *InstancePtr, XMmult_accel_core_Config *ConfigPtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(ConfigPtr != NULL);

    InstancePtr->Control_bus_BaseAddress = ConfigPtr->Control_bus_BaseAddress;
    InstancePtr->IsReady = XIL_COMPONENT_IS_READY;

    return XST_SUCCESS;
}
#endif

void XMmult_accel_core_Start(XMmult_accel_core *InstancePtr) {
    u32 Data;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMmult_accel_core_ReadReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_AP_CTRL) & 0x80;
    XMmult_accel_core_WriteReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_AP_CTRL, Data | 0x01);
}

u32 XMmult_accel_core_IsDone(XMmult_accel_core *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMmult_accel_core_ReadReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 1) & 0x1;
}

u32 XMmult_accel_core_IsIdle(XMmult_accel_core *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMmult_accel_core_ReadReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_AP_CTRL);
    return (Data >> 2) & 0x1;
}

u32 XMmult_accel_core_IsReady(XMmult_accel_core *InstancePtr) {
    u32 Data;

    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Data = XMmult_accel_core_ReadReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_AP_CTRL);
    // check ap_start to see if the pcore is ready for next input
    return !(Data & 0x1);
}

void XMmult_accel_core_EnableAutoRestart(XMmult_accel_core *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMmult_accel_core_WriteReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_AP_CTRL, 0x80);
}

void XMmult_accel_core_DisableAutoRestart(XMmult_accel_core *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMmult_accel_core_WriteReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_AP_CTRL, 0);
}

void XMmult_accel_core_InterruptGlobalEnable(XMmult_accel_core *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMmult_accel_core_WriteReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_GIE, 1);
}

void XMmult_accel_core_InterruptGlobalDisable(XMmult_accel_core *InstancePtr) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMmult_accel_core_WriteReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_GIE, 0);
}

void XMmult_accel_core_InterruptEnable(XMmult_accel_core *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMmult_accel_core_ReadReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_IER);
    XMmult_accel_core_WriteReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_IER, Register | Mask);
}

void XMmult_accel_core_InterruptDisable(XMmult_accel_core *InstancePtr, u32 Mask) {
    u32 Register;

    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    Register =  XMmult_accel_core_ReadReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_IER);
    XMmult_accel_core_WriteReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_IER, Register & (~Mask));
}

void XMmult_accel_core_InterruptClear(XMmult_accel_core *InstancePtr, u32 Mask) {
    Xil_AssertVoid(InstancePtr != NULL);
    Xil_AssertVoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    XMmult_accel_core_WriteReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_ISR, Mask);
}

u32 XMmult_accel_core_InterruptGetEnabled(XMmult_accel_core *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMmult_accel_core_ReadReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_IER);
}

u32 XMmult_accel_core_InterruptGetStatus(XMmult_accel_core *InstancePtr) {
    Xil_AssertNonvoid(InstancePtr != NULL);
    Xil_AssertNonvoid(InstancePtr->IsReady == XIL_COMPONENT_IS_READY);

    return XMmult_accel_core_ReadReg(InstancePtr->Control_bus_BaseAddress, XMMULT_ACCEL_CORE_CONTROL_BUS_ADDR_ISR);
}

